### ISSUE TITLE
Geoprocessing result created from dashboard does not show on map

### ISSUE THREAD

**Issue by neokore** [GeographicaGS/cartodb-geoprocessing-tools#59]
![image](https://cloud.githubusercontent.com/assets/938057/16236917/5c7071d6-37da-11e6-96b4-65f100cf0b3a.png)

if click ‘see dataset’ , the result can be seen in CartoDB Editor: and notice that the name is different > refer to issue I logged in issue 9 in the document (Try to delete the geoprocessing dataset, but it throw the error: Only happened for Geoprocessing outcome layers). 
![image](https://cloud.githubusercontent.com/assets/938057/16236922/61e3e724-37da-11e6-9db1-c74c6acf680d.png)

**Comment by neokore** [comment]
It seems to be a problem with the CartoDB API. It creates the table but somehow it returns `success: false` and `state: "failure"` when asking for this import; but when checking the result table on the CartoDB editor, it is working there.

An example to get this error is:
User: cartodbtest
Map: US test
Process: Union
Layers to operate: chicago_major_streets, chicago_bike_routes

This is an example of the response from the CartoDB API:

```
{
  content_guessing: false,
  create_visualization: false,
  data_type: "external_table",
  display_name: "378bff0a-a478-4257-b514-f06748f06f25",
  error_code: null,
  get_error_text: null,
  id: "378bff0a-a478-4257-b514-f06748f06f25",
  is_raster: false,
  original_url: "",
  queue_id: "378bff0a-a478-4257-b514-f06748f06f25",
  quoted_fields_guessing: true,
  state: "failure",
  success: false,
  synchronization_id: null,
  table_id: "b6ebc2c7-6ac6-42e7-9f96-edffcc3122ce",
  table_name: "unionbikesstreets",
  tables_created_count: 0,
  type_guessing: true,
  user_defined_limits: "{"twitter_credits_limit":0}",
  user_id: "0074b9a2-4132-48ef-b3bd-7da5bc0341fe",
  visualization_id: null,
  warnings: null
}
```

**Comment by danicarrion** [comment]
could you please post the request to the import api as well?

**Comment by neokore** [comment]
Sure!

Create import (POST):
URL: `https://edugis.smartgeo.sg/user/cartodbtest/api/v1/imports`
PARAMS: 
- `sql:with a as (select * from chicago_major_streets), b as (select * from chicago_bike_routes), all_lines as ( select (st_dump(the_geom)).geom  from a union all select (st_dump(the_geom)).geom  from b  ), noded_lines as ( select st_union(geom) as geom from all_lines ), non_intersect_lines as ( select distinct (st_dump(geom)).geom from noded_lines ) select l.geom as the_geom,a.streetname,a.r_fips,a.l_fips,a.t_zlev,a.f_zlev,a.rthund,a.rfhund,a.lthund,a.lfhund,a.ewns,a.logicrt,a.logicrf,a.logiclt,a.logiclf,a.r_t_add,a.r_f_add,a.l_t_add,a.l_f_add,a.old_trans_,a.source_id,a.trans_id,a.trans_,a.rpoly_,a.lpoly_,a.tnode_,a.fnode_,a.objectid,a.t_cross,a.f_cross,a.r_sect_nam,a.l_sect_nam,a.r_comarea,a.l_comarea,a.r_atom,a.l_atom,a.r_district,a.l_district,a.r_beat,a.l_beat,a.r_ilhouse,a.l_ilhouse,a.r_ilsenate,a.l_ilsenate,a.r_ward1990,a.l_ward1990,a.r_ward,a.l_ward,a.status,a.class,a.sufdir,a.suf_dir,a.sttype,a.street_typ,a.direction,a.pre_dir,a.r_parity,a.l_parity,a.edit_type,a.street,a.shape_len,a.length,a.updated_at,a.created_at,b.t_street,b.f_street,b.bikeroute,b.type,b.street as street_2,b.updated_at as updated_at_2,b.created_at as created_at_2 from non_intersect_lines l left join a on st_within(l.geom,a.the_geom) left join b on st_within(l.geom,b.the_geom)`
- `table_name:geoproctools_union_streets_bike`
- `privacy:public`
- `api_key: ...`

Check Import:
URL: `https://edugis.smartgeo.sg/user/cartodbtest/api/v1/imports/a7c12887-850c-40aa-8f43-eff9a517dfa1?api_key=eb34fb7b646fb8d95f66c5b87a8820969355be1a`

**Comment by danicarrion** [comment]
This is the corresponding log:

```
{:id=>"154fd43e-8242-4797-81af-732e159236f7", :type=>"import", :user_id=>"0074b9a2-4132-48ef-b3bd-7da5bc0341fe", :created_at=>2016-06-22 09:56:17 +0000, :updated_at=>2016-06-22 10:00:54 +0000, :entries=>"2016-06-22 09:56:21 UTC: Running on server edugis with PID: 4688\n2016-06-22 09:56:21 UTC: from_table()\n2016-06-22 09:56:21 UTC: import_from_query()\n2016-06-22 10:00:50 UTC: migrate_existing()\n2016-06-22 10:00:50 UTC: Table valid\n2016-06-22 10:00:54 UTC: Table 'unionbikesstreets' registered\n2016-06-22 10:00:54 UTC: After dispatch\n2016-06-22 10:00:54 UTC: Import finished\n\n2016-06-22 10:00:54 UTC: Exception: no implicit conversion of nil into String\n2016-06-22 10:00:54 UTC: [\"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:58:in `basename'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:31:in `send!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:812:in `notify'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:298:in `handle_success'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:191:in `run_import!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/importer_jobs.rb:9:in `block in perform'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/base_job.rb:21:in `call'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/base_job.rb:21:in `run_action'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/importer_jobs.rb:9:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'\", \"/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'\"]\n2016-06-22 10:00:54 UTC: ERROR!\n\n2016-06-22 10:00:54 UTC: Exception: no implicit conversion of nil into String\n2016-06-22 10:00:54 UTC: [\"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:58:in `basename'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:58:in `extract_file_names'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:31:in `send!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/services/importer/lib/importer/mail_notifier.rb:18:in `notify_if_needed'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:812:in `notify'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:330:in `handle_failure'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:204:in `rescue in run_import!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/app/models/data_import.rb:168:in `run_import!'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/importer_jobs.rb:9:in `block in perform'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/base_job.rb:21:in `call'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/base_job.rb:21:in `run_action'\", \"/home/ubuntu/www/production.cartodb.com/releases/20160309150424/lib/resque/importer_jobs.rb:9:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:240:in `block (3 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-metrics-0.1.1/lib/resque/metrics.rb:353:in `around_perform_metrics'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:239:in `block (2 levels) in perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/job.rb:247:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:250:in `perform'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:189:in `block in work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `loop'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/worker.rb:166:in `work'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/resque-1.25.2/lib/resque/tasks.rb:41:in `block (2 levels) in <top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `call'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:205:in `block in execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:200:in `execute'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:158:in `block in invoke_with_call_chain'\", \"/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:151:in `invoke_with_call_chain'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/task.rb:144:in `invoke'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:116:in `invoke_task'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block (2 levels) in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `each'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:94:in `block in top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:88:in `top_level'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:66:in `block in run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/gems/rake-0.9.2.2/bin/rake:33:in `<top (required)>'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `load'\", \"/home/ubuntu/www/production.cartodb.com/shared/bundle/ruby/2.2.0/bin/rake:23:in `<main>'\"]\n"}
```

**Comment by danicarrion** [comment]
It seems it's a problem with the email CartoDB tries to send after the import has finished. So the import was successful, but the API returns an error because of this.

I'm going to try and debug their email settings, will keep you posted.

**Comment by ernesmb** [comment]
Looks the same as: https://github.com/CartoDB/cartodb/issues/6296

[This](https://github.com/CartoDB/cartodb/pull/7153) should fix it

**Comment by ernesmb** [comment]
We have already applied the fix on their machine. Could you please retry the import?
cc/ @danicarrion

**Comment by neokore** [comment]
I've tried using the same example I told before and now it works Ok. Thanks!
